name: CI

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  LEAN_VERSION: stable

jobs:
#   build:
#     name: Build and Test
#     runs-on: ubuntu-latest
    
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Install system dependencies
#         run: |
#           sudo apt-get update
#           sudo apt-get install -y libcurl4-openssl-dev build-essential

#       - name: Setup Lean
#         run: |
#           curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y
#           echo "$HOME/.elan/bin" >> $GITHUB_PATH

#       - name: Set Lean version
#         run: |
#           elan toolchain install ${{ env.LEAN_VERSION }}
#           elan default ${{ env.LEAN_VERSION }}

#       - name: Verify tools
#         run: |
#           elan --version
#           lake --version
#           lean --version

#       - name: Cache Lean dependencies
#         uses: actions/cache@v4
#         with:
#           path: |
#             ~/.elan
#             .lake/build
#           key: lean-${{ env.LEAN_VERSION }}-${{ hashFiles('lakefile.lean', 'lean-toolchain') }}
#           restore-keys: |
#             lean-${{ env.LEAN_VERSION }}-

#       - name: Build project
#         run: |
#           lake build

#       - name: Run health check (no API key needed)
#         run: |
#           # Test that the executable runs without API calls
#           ./.lake/build/bin/blockfrost-test --help

#       - name: Run API tests
#         env:
#           BLOCKFROST_PROJECT_ID: ${{ secrets.BLOCKFROST_PROJECT_ID }}
#         run: |
#           if [ -n "$BLOCKFROST_PROJECT_ID" ]; then
#             ./.lake/build/bin/blockfrost-test health
#           else
#             echo "Skipping API tests - no BLOCKFROST_PROJECT_ID secret"
#           fi

  build-macos:
    name: Build on macOS
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          brew install curl

      - name: Setup Lean
        run: |
          curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y
          echo "$HOME/.elan/bin" >> $GITHUB_PATH

      - name: Set Lean version
        run: |
          elan toolchain install ${{ env.LEAN_VERSION }}
          elan default ${{ env.LEAN_VERSION }}

      - name: Cache Lean dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.elan
            .lake/build
          key: lean-macos-${{ env.LEAN_VERSION }}-${{ hashFiles('lakefile.lean', 'lean-toolchain') }}
          restore-keys: |
            lean-macos-${{ env.LEAN_VERSION }}-

      - name: Build project
        run: |
          lake build

      - name: Run health check
        env:
          BLOCKFROST_PROJECT_ID: ${{ secrets.BLOCKFROST_PROJECT_ID }}
        run: |
          ./.lake/build/bin/blockfrost-test