name: CI

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  LEAN_VERSION: stable

jobs:
  build-macos:
    name: Build on macOS
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          brew install curl

      - name: Setup Lean
        run: |
          curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y
          echo "$HOME/.elan/bin" >> $GITHUB_PATH

      - name: Set Lean version
        run: |
          elan toolchain install ${{ env.LEAN_VERSION }}
          elan default ${{ env.LEAN_VERSION }}

      - name: Cache Lean dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.elan
            .lake/build
          key: lean-macos-${{ env.LEAN_VERSION }}-${{ hashFiles('lakefile.lean', 'lean-toolchain') }}
          restore-keys: |
            lean-macos-${{ env.LEAN_VERSION }}-

      - name: Build project
        run: |
          lake build

      - name: Run health check
        env:
          BLOCKFROST_PROJECT_ID: ${{ secrets.BLOCKFROST_PROJECT_ID }}
        run: |
          ./.lake/build/bin/blockfrost-test